TaskSched: SimpleList< T > Class Template Reference
SimpleList< T > Class Template Reference
A simple linked list implementation.
#include <SimpleList.h>
Classes
class const_iterator
Iterator class for SimpleList.
class iterator
Public Member Functions
SimpleList ()
Construct a new empty SimpleList object.
~SimpleList ()
Destroy the SimpleList object and free all allocated memory.
void push_back (const T &value)
Add a new element to the end of the list.
void pop_front ()
Remove the first element from the list.
T read () const
Read the current element and move the read position to the next element.
void rewind () const
Reset the read position to the beginning of the list.
bool is_exhausted () const
Check if all elements have been read.
size_t get_size () const
Get the number of elements in the list.
void clear ()
Remove all elements from the list.
const_iterator cbegin () const
Get a const_iterator pointing to the beginning of the list.
const_iterator cend () const
Get a const_iterator pointing to the end of the list.
iterator begin () const
Get an iterator pointing to the beginning of the list.
iterator end () const
Get an iterator pointing to the end of the list.
Detailed Description
template<typename T>
class SimpleList< T >
A simple linked list implementation.
Template Parameters
T The type of elements stored in the list
Definition at line 11 of file SimpleList.h.
Constructor & Destructor Documentation
SimpleList()
template<typename T > SimpleList< T >::SimpleList () inline
Construct a new empty SimpleList object.
Definition at line 37 of file SimpleList.h.
 : head(nullptr), tail(nullptr), read_position(nullptr), size(0) {}
~SimpleList()
template<typename T > SimpleList< T >::~SimpleList () inline
Destroy the SimpleList object and free all allocated memory.
Definition at line 42 of file SimpleList.h.
                   {
         clear();
     }
References SimpleList< T >::clear().
Member Function Documentation
begin()
template<typename T > iterator SimpleList< T >::begin () const inline
Get an iterator pointing to the beginning of the list.
Returns
iterator Iterator to the first element
Definition at line 273 of file SimpleList.h.
 { return iterator(head); }
Referenced by Sched::run().
cbegin()
template<typename T > const_iterator SimpleList< T >::cbegin () const inline
Get a const_iterator pointing to the beginning of the list.
Returns
const_iterator Const iterator to the first element
Definition at line 204 of file SimpleList.h.
 { return const_iterator(head); }
cend()
template<typename T > const_iterator SimpleList< T >::cend () const inline
Get a const_iterator pointing to the end of the list.
Returns
const_iterator Const iterator to the element after the last element
Definition at line 211 of file SimpleList.h.
 { return const_iterator(nullptr); }
clear()
template<typename T > void SimpleList< T >::clear () inline
Remove all elements from the list.
Definition at line 123 of file SimpleList.h.
                  {
         while (head) {
             Node* temp = head;
             head = head->next;
             delete temp;
         }
         tail = nullptr;
         read_position = nullptr;
         size = 0;
     }
Referenced by SimpleList< T >::~SimpleList().
end()
template<typename T > iterator SimpleList< T >::end () const inline
Get an iterator pointing to the end of the list.
Returns
iterator Iterator to the element after the last element
Definition at line 280 of file SimpleList.h.
 { return iterator(nullptr); }
Referenced by Sched::run().
get_size()
template<typename T > size_t SimpleList< T >::get_size () const inline
Get the number of elements in the list.
Returns
size_t The number of elements
Definition at line 116 of file SimpleList.h.
{
         return size;
     }
Referenced by Sched::getSize().
is_exhausted()
template<typename T > bool SimpleList< T >::is_exhausted () const inline
Check if all elements have been read.
Returns
true if read_position is null, false otherwise
Definition at line 107 of file SimpleList.h.
{
         return read_position == nullptr;
     }
pop_front()
template<typename T > void SimpleList< T >::pop_front () inline
Remove the first element from the list.
Definition at line 65 of file SimpleList.h.
                      {
         if (head) {
             Node* temp = head;
             head = head->next;
             if (read_position == temp) {
                 read_position = head;
             }
             delete temp;
             --size;
             if (!head) {
                 tail = nullptr;
                 read_position = nullptr;
             }
         }
     }
push_back()
template<typename T > void SimpleList< T >::push_back (const T & value) inline
Add a new element to the end of the list.
Parameters
value The value to be added
Definition at line 51 of file SimpleList.h.
{
         Node* new_node = new Node(value);
         if (!head) {
             head = tail = read_position = new_node;
         } else {
             tail->next = new_node;
             tail = new_node;
         }
         ++size;
     }
Referenced by Sched::addTask().
read()
template<typename T > T SimpleList< T >::read () const inline
Read the current element and move the read position to the next element.
Returns
T The current element (empty T if read_position is null)
Definition at line 86 of file SimpleList.h.
                    {
         if (read_position) {
             T value = read_position->data;
             read_position = read_position->next;
             return value;
         }
         return T();  // Return empty T
     }
rewind()
template<typename T > void SimpleList< T >::rewind () const inline
Reset the read position to the beginning of the list.
Definition at line 98 of file SimpleList.h.
{
         read_position = head;
     }
The documentation for this class was generated from the following file:
SimpleList.h