TaskSched: Sched Class Reference
Sched Class Reference
This class runs the scheduled tasks.
#include <TaskSched.h>
Public Member Functions
unsigned long getSize ()
return the number of tasks in the run queue
String displayStatus (int num, String taskName="", bool raw=false)
Sched ()
void begin ()
void addTask (SafePtr< Task > task)
void enable ()
enable the scheduler
void disable ()
disable the scheduler
int isEnabled ()
return true if the scheduler is enabled
const SimpleList< SafePtr< Task > > & getTasks () const
void run ()
called perodically to check if a task should be scheduled
Detailed Description
This class runs the scheduled tasks.
Task* t = new Task(turnLedOn, 1000,true,20,"OnOff",true);
Task t1(turnLedOn, 100,false,20,"On1",false);
Task t2(turnLedOn, 2.0,false,20,"On2",false);
Output as generated by scheduler.displayStatus(true):
450 Task       On2,  Enabled? 0, Diff 00:15.735, Interval 00:02.000, RI 0
450 Task       On1,  Enabled? 0, Diff 00:15.735, Interval 00:00.100, RI 0
450 Task        On,  Enabled? 1, Diff 00:01.721, Interval 00:01.000, RI 0
It's kinda like the DTO in the Java world.
Definition at line 302 of file TaskSched.h.
Constructor & Destructor Documentation
Sched()
Sched::Sched ()
Definition at line 295 of file TaskSched.cpp.
              {
 }
Member Function Documentation
addTask()
void Sched::addTask (SafePtr< Task > task)
Example:
Task* t = new Task(turnLedOn, 1000,true,20,"OnOff",true);
Task t1(dummy, 100, false, 20, "On1", * false);
Task t2(dummy, 2.0, false, 20, "On2", * false);
    scheduler.addTask(t);
    scheduler.addTask(&t1);
    scheduler.addTask(&t2);
Definition at line 301 of file TaskSched.cpp.
 {
 #ifdef DEBUG
     Serial.printf("add called for task, %s %x\n",task->getName().c_str(),task);
 #endif
     tTasks.push_back(task);
     return;
 };
References SimpleList< T >::push_back().
begin()
void Sched::begin ()
used to start the scheduling. A call to begin will also enable the scheduler.
Sched scheduler;
    scheduler.begin();
Definition at line 298 of file TaskSched.cpp.
                   {
     this->mSchedEnabled=1;
 }
disable()
void Sched::disable ()
disable the scheduler
Definition at line 313 of file TaskSched.cpp.
                     {
     this->mSchedEnabled=0;
 }
displayStatus()
String Sched::displayStatus (int num, String taskName = "", bool raw = false)
function to display the status of the tasks
Sample output:
    Task       On2,  Enabled? 0, Diff 59:40.731, Interval 00:02.000, RI 0
    Task       On1,  Enabled? 0, Diff 59:40.731, Interval 00:00.100, RI 0
    Task        On,  Enabled? 0, Diff 59:19.710, Interval 00:01.000, RI 0
Source:
    String str = scheduler.displayStatus(true);
    Serial.print(str);
Returns
num = true show status of num tasks,
num = 0 show status of enabled tasks only
if taskName != "" ignore num setting
Definition at line 242 of file TaskSched.cpp.
{
     static char printBuffer[1000]; // used to display status
     char temp[1000];
     strcpy(temp,"");
     SimpleList<SafePtr<Task>>::iterator it;  // Changed from SimpleList<Task*>::iterator
     sprintf(printBuffer,"%s","");
     int cnt=0;
     for (it = tTasks.begin(); it != tTasks.end(); ++it){
         SafePtr<Task>& currentTask = *it;
         unsigned long diff = millis() - currentTask->getLastStartTime();
         String sDiff= currentTask->formatMS(diff);
         char sint[32];
         if(raw) {
             sprintf(sint,"%d",  currentTask->getInterval());
         } else {
             String sIntx= currentTask->formatMS(currentTask->getInterval());
             strcpy(sint,sIntx.c_str());
         }
         String sInt(sint);
         if(taskName!="") {
             String name = currentTask->getName();
             if(taskName == name) {
                 sprintf(temp,"%d Task %s, Enabled? %d, Diff %s, Interval %s, RI %d\n",cnt,currentTask->getName().c_str(),currentTask->isEnabled(),sDiff.c_str(),sInt.c_str(),currentTask->getRunImmediately());
                 strcat(printBuffer,temp);
             }
         } else if(!num && currentTask->isEnabled()) {
             if(!currentTask->isEnabled()) {
                 //         Serial.printf("Skip %x\n",currentTask);
                 continue;
             }
             //                    sprintf(temp,"Task %s, Enabled? %d Diff %s, Interval %s, RI %d\n",currentTask->getName(),currentTask->isEnabled(),sDiff,sInt,currentTask->getRunImmediately());
             cnt++;
             sprintf(temp,"%d Task %s, Enabled? %d, Diff %s, Interval %s, RI %d\n",cnt,currentTask->getName().c_str(),currentTask->isEnabled(),sDiff.c_str(),sInt.c_str(),currentTask->getRunImmediately());
             //    Serial.printf("  Temp %s\n",temp);
             //   Serial.printf("%ld dif %s\n",__LINE__, sDiff.c_str());
             strcat(printBuffer,temp);
         } else if(num) {
             if(cnt>num) {
                 break;
             }
             sprintf(temp,"Task %9s,  Enabled? %d, Diff %s, Interval %s, RI %d\n", currentTask->getName().c_str(), currentTask->isEnabled(),sDiff.c_str(),sInt.c_str(),currentTask->getRunImmediately());
             //sprintf(temp,"Task %s, Diff %lu, Interval %lu, enabled %d, RI %d\n",currentTask->getName(),diff,currentTask->getInterval(),currentTask->isEnabled(),currentTask->getRunImmediately());
             //                    Serial.printf("%ld dif %s\n",__LINE__, sDiff.c_str());
             if(strlen(temp)+strlen(printBuffer)<999) {
                 strcat(printBuffer,temp);
             }
         }
     }
     String retStr(printBuffer);
     return retStr;
 }
References SimpleList< T >::begin(), and SimpleList< T >::end().
enable()
void Sched::enable ()
enable the scheduler
Definition at line 310 of file TaskSched.cpp.
                    {
     this->mSchedEnabled=1;
 }
getSize()
unsigned long Sched::getSize ()
return the number of tasks in the run queue
Returns
Definition at line 232 of file TaskSched.cpp.
 {
     return tTasks.get_size();
 }
References SimpleList< T >::get_size().
getTasks()
const SimpleList< SafePtr< Task > > & Sched::getTasks () const
Definition at line 348 of file TaskSched.cpp.
 {
     return tTasks;
 }
isEnabled()
int Sched::isEnabled ()
return true if the scheduler is enabled
Returns
Definition at line 316 of file TaskSched.cpp.
                      {
     return this->mSchedEnabled;
 }
run()
void Sched::run ()
called perodically to check if a task should be scheduled
Definition at line 322 of file TaskSched.cpp.
 {
     if(this->mSchedEnabled) {
 #ifdef DEBUG
         //                Serial.println("Looking for tasks");
 #endif
 //        SimpleList<SafePtr<Task> task>::iterator it;
         for (auto it = tTasks.begin(); it != tTasks.end(); ++it) {
  //       for (it = tTasks.begin(); it != tTasks.end(); ++it){
             SafePtr<Task>& currentTask = *it;
 #ifdef DEBUGR
             Serial.printf("%s %d task=%x i=%d millis()=%ld Found name=%s, Is enabled? %d\n",__FILE__,__LINE__,currentTask,i++,millis(),currentTask->getName().c_str(),currentTask->isEnabled());
             currentTask->showInit();
 #endif
             if(currentTask->isEnabled()) {
                 currentTask->runIt();
             }
         }
     } else {
 #ifdef DEBUG
         Serial.println("Not enabled");
 #endif
     }
 }
References SimpleList< T >::begin(), and SimpleList< T >::end().
The documentation for this class was generated from the following files:
TaskSched.h
TaskSched.cpp