TaskSched: Task Class Reference
Task Class Reference
Represents a schedulable task.
#include <TaskSched.h>
Public Types
typedef void(* TaskCallback) (Task *)
typedef void(* VoidCallback) ()
Public Member Functions
Task (TaskCallback func, unsigned long interval=5000, bool enabled=false, int iterations=0, const char *name="Unk", bool runImmediately=false)
Constructs a new Task.
Task (VoidCallback func, unsigned long interval=5000, bool enabled=false, int iterations=0, const char *name="Unk", bool runImmediately=false)
SafePtr< Task > getSafePtr ()
Gets a SafePtr to this Task.
bool isFirstIteration ()
return true if this is the first iteration
bool isLastIteration ()
return true if this is the last iteration
bool fRunImmediately ()
return true if the run immediately flag is set
void restart ()
restart the task with the original parameters, Enable is not restored
void enable ()
enable the task
void disable ()
disable the task
bool isEnabled ()
return true if task is enabled
void setCallback (const TaskCallback &callback)
Sets a new callback function for the task.
void setCallback (const VoidCallback &callback)
Sets a new callback function for the task.
void setName (String)
give the task a new name
void runIt ()
function used by the schedule to run this task, shouldn't be called by user
void showInit ()
display stuff
String getName ()
return string containing name of task
unsigned long getIterationCount ()
return the iteration count, that is the number of iterations that the task has been run
void setInterval (unsigned long newInterval)
function to set a new interval
void setIterations (unsigned long newIterations)
function to set a new iterations value
void setImmediately (bool)
function to set the run immediately flag
String showTaskInfo ()
function that displays task info
unsigned long getInterval (void)
return the task interval
bool getRunImmediately (void)
return the run immediately flag
unsigned long getLastStartTime (void)
return the last start time flag
String formatMS (unsigned long milliseconds)
return a string with a formatted time
Public Attributes
int mIntI
Detailed Description
Represents a schedulable task.
Define a new Task.
Parameters
func Function to be called at regular intervals.
interval Time between calls to func, specified in milliseconds or seconds. If interval is a floating-point value, it's interpreted as seconds; otherwise, it's treated as milliseconds.
enabled Flag to indicate whether the task should start in an enabled state (true) or disabled state (false).
iterations Number of times the task will be executed. Set to 0 for infinite iterations.
name A descriptive string name for the task.
runImmediately Boolean flag determining whether to run the callback immediately (true) or wait for the interval to expire (false).
Task* t = new Task(turnLedOn, 1000,true,20,"OnOff",true);
Task t1(turnLedOn, 1000,false,100,"On1",false);
Task t2(turnLedOn, 2000,false,2000,"On2",false);
Output:
450 Task       On2,  Enabled? 0, Diff 00:15.735, Interval 00:02.000, RI 1
450 Task       On1,  Enabled? 0, Diff 00:15.735, Interval 00:00.100, RI 0
450 Task        On,  Enabled? 1, Diff 00:01.721, Interval 00:01.000, RI 0
The Task class encapsulates a function to be called at regular intervals, along with parameters controlling its execution.
Definition at line 81 of file TaskSched.h.
Member Typedef Documentation
TaskCallback
typedef void(* Task::TaskCallback) (Task *)
Definition at line 85 of file TaskSched.h.
VoidCallback
typedef void(* Task::VoidCallback) ()
Definition at line 86 of file TaskSched.h.
Constructor & Destructor Documentation
Task() [1/2]
Task::Task (TaskCallback func, unsigned long interval = 5000, bool enabled = false, int iterations = 0, const char * name = "Unk", bool runImmediately = false)
Constructs a new Task.
Template Parameters
T Type of the interval (can be integral or floating-point)
Parameters
func Function to be called at regular intervals
interval Time between calls to func (in milliseconds if integral, seconds if floating-point)
enabled Flag to indicate whether the task should start in an enabled state
iterations Number of times the task will be executed (0 for infinite)
name A descriptive name for the task
runImmediately Whether to run the callback immediately or wait for the interval
Returns
The first form returns a pointer to the task, the second does not.
Definition at line 7 of file TaskSched.cpp.
     : mProcWithTask(func), mProcVoid(nullptr), mWithTaskPtr(true)
 {
     // Initialize other members...
             //mProc=func;
             mInterval=interval;
             mEnabled=enabled;
             mIterations=iterations;
             mName=name;
             mRunImmediately=runImmediately;
             mOrig.mEnabled=enabled;
             mOrig.mInterval=mInterval;
             mOrig.mIterations=iterations;
             mOrig.mRunImmediately=runImmediately;
             mLastStartTime=millis();
             mIterationCount=0;
 }
References InitialState::mEnabled, InitialState::mInterval, InitialState::mIterations, and InitialState::mRunImmediately.
Task() [2/2]
Task::Task (VoidCallback func, unsigned long interval = 5000, bool enabled = false, int iterations = 0, const char * name = "Unk", bool runImmediately = false)
Definition at line 25 of file TaskSched.cpp.
     : mProcWithTask(nullptr), mProcVoid(func), mWithTaskPtr(false)
 {
     // Initialize other members...
             //mProc=func;
             mInterval=interval;
             mEnabled=enabled;
             mIterations=iterations;
             mName=name;
             mRunImmediately=runImmediately;
             mOrig.mEnabled=enabled;
             mOrig.mInterval=interval;
             mOrig.mIterations=iterations;
             mOrig.mRunImmediately=runImmediately;
             mLastStartTime=millis();
             mIterationCount=0;
 }
References InitialState::mEnabled, InitialState::mInterval, InitialState::mIterations, and InitialState::mRunImmediately.
Member Function Documentation
disable()
void Task::disable ()
disable the task
Definition at line 66 of file TaskSched.cpp.
                    {
     mEnabled=false;
     mIterationCount=0;
     return;
 }
Referenced by runIt().
enable()
void Task::enable ()
enable the task
Definition at line 127 of file TaskSched.cpp.
                   {
     mEnabled=true;
     mLastStartTime=millis();
 #ifdef DEBUG
     Serial.printf("Enabling %s\n",mName.c_str());
 #endif
     return;
 }
formatMS()
String Task::formatMS (unsigned long milliseconds)
return a string with a formatted time
Returns
Definition at line 87 of file TaskSched.cpp.
{
     int minutes = milliseconds / 60000;
     int seconds = (milliseconds % 60000) / 1000;
     int ms = (milliseconds % 1000);
     char res[20];
     sprintf(res, "%02d:%02d.%03d", minutes, seconds, ms);
 #ifdef DEBUG
     Serial.printf("%s %d %s\n",__FILE__,__LINE__,res);
 #endif
     return String(res);
 }
Referenced by runIt(), showInit(), and showTaskInfo().
fRunImmediately()
bool Task::fRunImmediately ()
return true if the run immediately flag is set
Returns
getInterval()
unsigned long Task::getInterval (void)
return the task interval
Returns
Definition at line 182 of file TaskSched.cpp.
 {
     return mInterval;
 }
Referenced by runIt(), and showTaskInfo().
getIterationCount()
unsigned long Task::getIterationCount ()
return the iteration count, that is the number of iterations that the task has been run
Returns
Definition at line 192 of file TaskSched.cpp.
 {
     return mIterationCount;
 }
getLastStartTime()
unsigned long Task::getLastStartTime (void)
return the last start time flag
Returns
Definition at line 187 of file TaskSched.cpp.
 {
     return mLastStartTime;
 }
Referenced by runIt(), and showTaskInfo().
getName()
String Task::getName ()
return string containing name of task
Returns
Definition at line 50 of file TaskSched.cpp.
 {
     return mName;
 }
Referenced by runIt(), and showTaskInfo().
getRunImmediately()
bool Task::getRunImmediately (void)
return the run immediately flag
Returns
Definition at line 177 of file TaskSched.cpp.
 {
     return mRunImmediately;
 }
Referenced by runIt(), and showTaskInfo().
getSafePtr()
SafePtr<Task> Task::getSafePtr () inline
Gets a SafePtr to this Task.
Returns
SafePtr<Task> A safe pointer to this Task
Definition at line 163 of file TaskSched.h.
{
         return SafePtr<Task>(this);
     }
isEnabled()
bool Task::isEnabled ()
return true if task is enabled
Returns
Definition at line 123 of file TaskSched.cpp.
                      {
     return mEnabled;
 }
Referenced by runIt(), and showTaskInfo().
isFirstIteration()
bool Task::isFirstIteration ()
return true if this is the first iteration
Returns
Definition at line 43 of file TaskSched.cpp.
{
     if(mIterationCount == 0) {
         return true;
     }
     return false;
 }
isLastIteration()
bool Task::isLastIteration ()
return true if this is the last iteration
Returns
Definition at line 55 of file TaskSched.cpp.
{
 //    Serial.printf("count = %ld, Iter = %ld\n",mIterationCount,mIterations);
     if(mIterations <= 0) {
         return false;
     }
     if(mIterationCount >=mIterations-1) {
         return true;
     }
     return false;
 }
restart()
void Task::restart ()
restart the task with the original parameters, Enable is not restored
Definition at line 136 of file TaskSched.cpp.
                    {
     mInterval=mOrig.mInterval;
     mIterations=mOrig.mIterations;
     mEnabled=false;
     mIterationCount=0;
     mRunImmediately=mOrig.mRunImmediately;
 #ifdef DEBUG
     Serial.printf("Restarting %s\n",mName.c_str());
 #endif
     return;
 }
References InitialState::mInterval, InitialState::mIterations, and InitialState::mRunImmediately.
runIt()
void Task::runIt ()
function used by the schedule to run this task, shouldn't be called by user
Definition at line 196 of file TaskSched.cpp.
                  {
     if (!isEnabled()) {
         return;
     }
     if ((mRunImmediately && mIterationCount == 0) || (millis() - mLastStartTime) > mInterval) {
         mRunImmediately = false;
         unsigned long diff = millis() - getLastStartTime();
         String sDiff= formatMS(diff);
         String sInt= formatMS(getInterval());
 #ifdef DEBUG
         Serial.printf("%s %d Task %s, Enabled? %d, Diff %s, Interval %s, RI %d\n",__FILE__,__LINE__,getName().c_str(),isEnabled(),sDiff.c_str(),sInt.c_str(),getRunImmediately());
 #endif
         if (mWithTaskPtr && mProcWithTask) {
             mProcWithTask(this);
         } else if (!mWithTaskPtr && mProcVoid) {
             mProcVoid();
         }
         ++(mIterationCount);
 #ifdef DEBUG
         Serial.printf("%s %d %s in runit iteration count is %ld, max is %ld\n",__FILE__,__LINE__,getName().c_str(),mIterationCount,mIterations);
 #endif
         if(mIterationCount>=mIterations && mIterations != 0) {
             disable();
         } else {
             mLastStartTime=millis();
         }
 #ifdef DEBUG
         //        Serial.printf("%s in runit count is %ld\n",getName(),mIterationCount);
 #endif
     }
 }
References disable(), formatMS(), getInterval(), getLastStartTime(), getName(), getRunImmediately(), and isEnabled().
setCallback() [1/2]
void Task::setCallback (const TaskCallback & callback)
Sets a new callback function for the task.
Parameters
callback The new callback function
Definition at line 153 of file TaskSched.cpp.
{
     //mProc=func;
     mProcWithTask=func;
 }
setCallback() [2/2]
void Task::setCallback (const VoidCallback & callback)
Sets a new callback function for the task.
Parameters
callback The new callback function
Definition at line 148 of file TaskSched.cpp.
{
     //mProc=func;
     mProcVoid=func;
 }
setImmediately()
void Task::setImmediately (bool newImmediately)
function to set the run immediately flag
Definition at line 162 of file TaskSched.cpp.
 {
     mRunImmediately = newImmediately;
 }
setInterval()
void Task::setInterval (unsigned long newInterval)
function to set a new interval
Definition at line 172 of file TaskSched.cpp.
 {
     mInterval = newInterval;
 }
setIterations()
void Task::setIterations (unsigned long newIterations)
function to set a new iterations value
Definition at line 167 of file TaskSched.cpp.
 {
     mIterations = newIterations;
 }
setName()
void Task::setName (String newName)
give the task a new name
Definition at line 158 of file TaskSched.cpp.
{
     mName=newName;
 }
showInit()
void Task::showInit ()
display stuff
Definition at line 72 of file TaskSched.cpp.
                     {
     if(!doShow) {
         return;
     }
     doShow=false; // only do it once
 #ifdef DEBUG
     res = formatMS(mInterval);
     Serial.printf("%s %d showInit: Name: %s, interval: %s, enabled:%d, iterations:%ld %x\n",
             __FILE__,__LINE__,mName,res,mEnabled,mIterations,this);
 #endif
     return;
 }
References formatMS().
showTaskInfo()
String Task::showTaskInfo ()
function that displays task info
Returns
String containing info about all tasks tasks.
Definition at line 102 of file TaskSched.cpp.
{
     char buf[200];
     unsigned long diff = millis() - getLastStartTime();
     String sDiff= formatMS(diff);
     String sInt= formatMS(getInterval());
 #ifdef DEBUG
     Serial.printf("%s %d Task %s, Enabled? %d, Diff %s, Interval %s, RI %d\n",__FILE__,__LINE__,this->getName().c_str(),isEnabled(),sDiff.c_str(),sInt.c_str(),getRunImmediately());
     if(passedInterval >0) {
         Serial.printf("For float interval passed in %f, mInterval became %ld\n",passedInterval,mInterval);
     }
 #else
     sprintf(buf,"Task %s, Enabled? %d, Diff %s, Interval %s, RunIm %d\n",this->getName().c_str(),isEnabled(),sDiff.c_str(),sInt.c_str(),getRunImmediately());
     String ret(buf);
     return ret;
 #endif
     return "";
 }
References formatMS(), getInterval(), getLastStartTime(), getName(), getRunImmediately(), and isEnabled().
Member Data Documentation
mIntI
int Task::mIntI
Usage:
SaafePtr<Task> createTask(parameters) { Task* rawTask = new Task(parameters); return rawTask->getSaafePtr(); }
Returns
Definition at line 179 of file TaskSched.h.
The documentation for this class was generated from the following files:
TaskSched.h
TaskSched.cpp